# -*- coding: utf-8 -*-
"""lime_agentic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXNfxPJHbOdNUEKw5OdmM1Br3cFehuPA

# SET GENERATOR
"""

LLM_Model = 'Gemini'

#Gemini API

!pip install -q -U google-generativeai

import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown

def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))
# Used to securely store your API key
from google.colab import userdata

# Or use `os.getenv('GOOGLE_API_KEY')` to fetch an environment variable.
#GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
GOOGLE_API_KEY = 'AIzaSyA1LJxSW2QccN-jdVBpN751KEnPFcq0adU'
genai.configure(api_key=GOOGLE_API_KEY)

#model available list
for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-1.5-flash')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content("What is the meaning of life?")

#pure ask
def ask_gemini(query):

  response = model.generate_content(query)
  return response.text

if LLM_Model == 'Gemini':
  def generator(query):
     return ask_gemini(query)

"""# BUILD"""

import re

def extract_pattern(text):
  # Extracting the "Thinking" part
  thinking_match = re.search(r'## Thinking\n\n(.*?)\n\n## Evidence', text, re.DOTALL)
  thinking_part = thinking_match.group(1).strip() if thinking_match else ""

  # Extracting the "Evidence" part
  evidence_match = re.findall(r'\d+\.\s+"(.*?)"', text)
  evidence_list = evidence_match if evidence_match else []
  return thinking_part, evidence_list

def find_evidence(problem):
  prompt = f'''You are a professional problem solver. For the given problem:{problem}, first, develop a step-by-step plan to solve it. Then, gather concrete evidence from the problem description that is crucial in finding the solution. The evidence must consist of the original words or sentences that appear in the problem statement and evidences are not overlapped.
    the output format is:
    ## Thinking
    content
    ## Evidence
    1.(content1)
    2.(content2)
    ...'''
  result =  generator(prompt)
  thinking, evidences = extract_pattern(result)
  return thinking, evidences

def extract_answer(text):
  # Extract the final answer using regex
  match = re.search(r'@Final Answer:\s*(\d+)', text)

  # Get the final answer if found
  final_answer = match.group(1) if match else None

  # Display the extracted final answer
  return final_answer

def find_solution(thinking, problem):
  prompt = f'''for the problem:{problem}. based on the thinking:{thinking}, answer the question.and for the final answer , the ouput format is:
  ......
  @Final Answer: answer'''
  result =  generator(prompt)
  answer = extract_answer(result)
  return result, answer




def solve_problem(problem):
  thinking, evidences = find_evidence(problem)
  solution, answer = find_solution(thinking, problem)
  return thinking, evidences, solution, answer

thinking, evidences, solution, answer = solve_problem('Tony is a driver , and Alice is a teacher, Find the best web tool.')
to_markdown(thinking)
print(evidences)
to_markdown(solution)
print(answer)

"""# LIME"""

import re

def validate_solution(problem, right_answer):
    # Step 1: Solve the problem with all information
    thinking, evidences, solution, answer = solve_problem(problem)

    # Step 2: Check if the initial answer is correct
    is_correct = (answer == right_answer)

    # Step 3: Test the importance of each evidence
    altered_answers = []
    for evidence in evidences:
        # Remove evidence from the problem statement
        modified_problem = problem.replace(evidence, "")

        # Solve the problem again with the modified input
        _, _, modified_solution, modified_answer = solve_problem(modified_problem)

        # Check if the answer has changed
        altered_answers.append((evidence, modified_answer, modified_answer == right_answer))

    return {
        "original_solution": solution,
        "original_correct": is_correct,
        "evidence_analysis": altered_answers
    }

# Example Usage
problem = "Find the sum of 5 and 3."
right_answer = "8"
result = validate_solution(problem, right_answer)
to_markdown(result['original_solution'])
print(result['evidence_analysis'])
print(result['original_correct'])



"""# RUN BATCH

data
"""

!pip install datasets

from huggingface_hub import login
import pandas as pd

login("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")

from datasets import load_dataset

dataset = load_dataset("cais/hle", split="test")

df = pd.DataFrame(dataset)
df

# prompt: 使用 DataFrame“df”: remain the rows that 'image'=='', and answer_type=='multichoice'
# then for every row use validate_solution(), record "original_solution": solution,
#         "original_correct": is_correct,
#         "evidence_analysis": altered_answers
# to different columns , then save the file

import pandas as pd


# Assuming your dataframe is named 'df'
# Filter the DataFrame
df_filtered = df[(df['image'] == '') & (df['answer_type'] == 'multichoice')]

# Apply the validation function and store results
results = []
for index, row in df_filtered.iterrows():
    result = validate_solution(row['question'],row['answer'])
    original_solution = result['original_solution']
    original_correct = result['original_correct']
    evidence_analysis = result['evidence_analysis']
    row['original_solution'] = original_solution
    row['original_correct'] = original_correct
    row['evidence_analysis'] = evidence_analysis


# Save the final DataFrame to a file (e.g., CSV)
df_filtered.to_csv("processed_multichoice_data.csv", index=False) #Change the filename as necessary

import pandas as pd
import os

# Define output file
output_file = "processed_multichoice_data.csv"

# Load the existing file if it exists
if os.path.exists(output_file):
    df_existing = pd.read_csv(output_file)
else:
    df_existing = None

# Filter the DataFrame
df_filtered = df[(df['image'] == '') & (df['answer_type'] == 'multipleChoice')]

# Initialize lists for batch processing
batch_size = 20
processed_rows = []
total_rows = len(df_filtered)
processed_count = 0

df_filtered['original_solution'] = [''] * len(df_filtered)

for index, row in df_filtered.iterrows():
    # Skip if the row is already processed
    if row['original_solution']!='':
        continue

    # Apply the validation function
    result = validate_solution(row['question'], row['answer'])
    row['original_solution'] = result['original_solution']
    row['original_correct'] = result['original_correct']
    row['evidence_analysis'] = result['evidence_analysis']

    # Track processed count
    processed_count += 1
    print(f"Processing {processed_count}/{total_rows}")

    # Collect processed row
    processed_rows.append(row)

    # Save every batch_size rows
    if len(processed_rows) >= batch_size:
        temp_df = pd.DataFrame(processed_rows)
        if os.path.exists(output_file):
            temp_df.to_csv(output_file, mode='a', index=False, header=False)  # Append without header
        else:
            temp_df.to_csv(output_file, index=False)  # Create file with header
        processed_rows = []  # Clear batch

# Save any remaining rows after the loop
if processed_rows:
    temp_df = pd.DataFrame(processed_rows)
    if os.path.exists(output_file):
        temp_df.to_csv(output_file, mode='a', index=False, header=False)
    else:
        temp_df.to_csv(output_file, index=False)

print("Processing complete!")

"""# EVALUATION"""